/* auto generate by HHB_VERSION 2.4.5 */

#include <csi_nn.h>

void *csinn_(char *params_base) {
  struct csinn_session *sess = csinn_alloc_session();
  sess->base_run_mode = CSINN_RM_CPU_GRAPH;
  sess->base_quant_type = CSINN_QUANT_FLOAT16;
  sess->model.save_mode = CSINN_RUN_ONLY;
  sess->base_api = CSINN_C920;
  sess->base_dtype = CSINN_DTYPE_FLOAT16;
  sess->dynamic_shape = CSINN_FALSE;
  csinn_session_init(sess);
  csinn_set_input_number(1, sess);
  csinn_set_output_number(1, sess);

  struct csinn_tensor *output_1[2];
  struct csinn_tensor *_model_22_Concat_3_output_0 = csinn_alloc_tensor(sess);
  _model_22_Concat_3_output_0->name = "_model_22_Concat_3_output_0@@split_/model.22/Split_0_1";
  _model_22_Concat_3_output_0->dtype = CSINN_DTYPE_FLOAT16;
  _model_22_Concat_3_output_0->layout = CSINN_LAYOUT_NCW;
  _model_22_Concat_3_output_0->dim[0] = 1;
  _model_22_Concat_3_output_0->dim[1] = 66;
  _model_22_Concat_3_output_0->dim[2] = 8400;
  _model_22_Concat_3_output_0->dim_count = 3;
  _model_22_Concat_3_output_0->qinfo = (struct csinn_quant_info *)(params_base + 0);
  _model_22_Concat_3_output_0->quant_channel = 1;
  struct csinn_tensor *output_1_0 = csinn_alloc_tensor(sess);
  output_1_0->name = "output_1_0";
  output_1_0->dtype = CSINN_DTYPE_FLOAT16;
  output_1_0->layout = CSINN_LAYOUT_NCW;
  output_1_0->dim[0] = 1;
  output_1_0->dim[1] = 64;
  output_1_0->dim[2] = 8400;
  output_1_0->dim_count = 3;
  output_1_0->qinfo = (struct csinn_quant_info *)(params_base + 24);
  output_1_0->quant_channel = 1;
  output_1[0] = output_1_0;
  struct csinn_tensor *output_1_1 = csinn_alloc_tensor(sess);
  output_1_1->name = "output_1_1";
  output_1_1->dtype = CSINN_DTYPE_FLOAT16;
  output_1_1->layout = CSINN_LAYOUT_NCW;
  output_1_1->dim[0] = 1;
  output_1_1->dim[1] = 2;
  output_1_1->dim[2] = 8400;
  output_1_1->dim_count = 3;
  output_1_1->qinfo = (struct csinn_quant_info *)(params_base + 48);
  output_1_1->quant_channel = 1;
  output_1[1] = output_1_1;
  int32_t *indices_or_sections_1 = malloc(sizeof(int32_t) * 1);
  indices_or_sections_1[0] = 64;;
  struct csinn_split_params *params_1 = csinn_alloc_params(sizeof(struct csinn_split_params), sess);
  params_1->split_index = indices_or_sections_1;
  params_1->output_num = 2;
  params_1->axis = 1;
  params_1->base.name = "split_/model.22/Split_0";
  params_1->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_split_init(_model_22_Concat_3_output_0, output_1, params_1);
  int32_t *shape_2 = malloc(4 * 4);
  shape_2[0] = 1;
  shape_2[1] = 4;
  shape_2[2] = 16;
  shape_2[3] = 8400;
  struct csinn_tensor *output_2 = csinn_alloc_tensor(sess);
  output_2->name = "output_2";
  output_2->dtype = CSINN_DTYPE_FLOAT16;
  output_2->layout = CSINN_LAYOUT_NCHW;
  output_2->dim[0] = 1;
  output_2->dim[1] = 4;
  output_2->dim[2] = 16;
  output_2->dim[3] = 8400;
  output_2->dim_count = 4;
  output_2->qinfo = (struct csinn_quant_info *)(params_base + 72);
  output_2->quant_channel = 1;
  struct csinn_reshape_params *params_2 = csinn_alloc_params(sizeof(struct csinn_reshape_params), sess);
  params_2->shape = shape_2;
  params_2->shape_num = 4;
  params_2->base.name = "reshape_/model.22/dfl/Reshape_1";
  params_2->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_reshape_init(output_1_0, output_2, params_2);
  int32_t *permute_3 = malloc(4 * 4);
  permute_3[0] = 0;
  permute_3[1] = 3;
  permute_3[2] = 1;
  permute_3[3] = 2;
  struct csinn_tensor *output_3 = csinn_alloc_tensor(sess);
  output_3->name = "output_3";
  output_3->dtype = CSINN_DTYPE_FLOAT16;
  output_3->layout = CSINN_LAYOUT_NCHW;
  output_3->dim[0] = 1;
  output_3->dim[1] = 8400;
  output_3->dim[2] = 4;
  output_3->dim[3] = 16;
  output_3->dim_count = 4;
  output_3->qinfo = (struct csinn_quant_info *)(params_base + 96);
  output_3->quant_channel = 1;
  struct csinn_transpose_params *params_3 = csinn_alloc_params(sizeof(struct csinn_transpose_params), sess);
  params_3->permute = permute_3;
  params_3->permute_num = 4;
  params_3->base.name = "transpose_/model.22/dfl/Transpose_2";
  params_3->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_transpose_init(output_2, output_3, params_3);
  struct csinn_tensor *output_4 = csinn_alloc_tensor(sess);
  output_4->name = "output_4";
  output_4->dtype = CSINN_DTYPE_FLOAT16;
  output_4->layout = CSINN_LAYOUT_NCHW;
  output_4->dim[0] = 1;
  output_4->dim[1] = 8400;
  output_4->dim[2] = 4;
  output_4->dim[3] = 16;
  output_4->dim_count = 4;
  output_4->qinfo = (struct csinn_quant_info *)(params_base + 120);
  output_4->quant_channel = 1;
  struct csinn_softmax_params *params_4 = csinn_alloc_params(sizeof(struct csinn_softmax_params), sess);
  params_4->axis = 3;
  params_4->base.name = "softmax_/model.22/dfl/Softmax_3";
  params_4->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_softmax_init(output_3, output_4, params_4);
  int32_t *permute_5 = malloc(4 * 4);
  permute_5[0] = 0;
  permute_5[1] = 3;
  permute_5[2] = 2;
  permute_5[3] = 1;
  struct csinn_tensor *output_5 = csinn_alloc_tensor(sess);
  output_5->name = "output_5";
  output_5->dtype = CSINN_DTYPE_FLOAT16;
  output_5->layout = CSINN_LAYOUT_NCHW;
  output_5->dim[0] = 1;
  output_5->dim[1] = 16;
  output_5->dim[2] = 4;
  output_5->dim[3] = 8400;
  output_5->dim_count = 4;
  output_5->qinfo = (struct csinn_quant_info *)(params_base + 144);
  output_5->quant_channel = 1;
  struct csinn_transpose_params *params_5 = csinn_alloc_params(sizeof(struct csinn_transpose_params), sess);
  params_5->permute = permute_5;
  params_5->permute_num = 4;
  params_5->base.name = "transpose_/model.22/dfl/Transpose_1_4";
  params_5->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_transpose_init(output_4, output_5, params_5);
  struct csinn_tensor *bias_6 = csinn_alloc_tensor(sess);
  bias_6->data = NULL;
  bias_6->name = "bias_6";
  bias_6->is_const = 1;
  bias_6->dim_count = 0;
  struct csinn_tensor *output_6 = csinn_alloc_tensor(sess);
  output_6->name = "output_6";
  output_6->dtype = CSINN_DTYPE_FLOAT16;
  output_6->layout = CSINN_LAYOUT_NCHW;
  output_6->dim[0] = 1;
  output_6->dim[1] = 1;
  output_6->dim[2] = 4;
  output_6->dim[3] = 8400;
  output_6->dim_count = 4;
  output_6->qinfo = (struct csinn_quant_info *)(params_base + 168);
  output_6->quant_channel = 1;
  struct csinn_tensor *kernel_6 = csinn_alloc_tensor(sess);
  kernel_6->name = "kernel_6";
  kernel_6->data = params_base + 216;
  kernel_6->is_const = 1;
  kernel_6->dtype = CSINN_DTYPE_FLOAT16;
  kernel_6->layout = CSINN_LAYOUT_OIHW;
  kernel_6->dim[0] = 1;
  kernel_6->dim[1] = 16;
  kernel_6->dim[2] = 1;
  kernel_6->dim[3] = 1;
  kernel_6->dim_count = 4;
  kernel_6->qinfo = (struct csinn_quant_info *)(params_base + 192);
  kernel_6->quant_channel = 1;
  struct csinn_conv2d_params *params_6 = csinn_alloc_params(sizeof(struct csinn_conv2d_params), sess);
  params_6->group = 1;
  params_6->stride_height = 1;
  params_6->stride_width = 1;
  params_6->dilation_height = 1;
  params_6->dilation_width = 1;
  params_6->conv_extra.kernel_tm = NULL;
  params_6->conv_extra.conv_mode = CSINN_DIRECT;
  params_6->pad_top = 0;
  params_6->pad_left = 0;
  params_6->pad_down = 0;
  params_6->pad_right = 0;
  params_6->base.name = "conv2d_/model.22/dfl/conv/Conv_5";
  params_6->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_conv2d_init(output_5, output_6, kernel_6, bias_6, params_6);
  int32_t *shape_7 = malloc(3 * 4);
  shape_7[0] = 1;
  shape_7[1] = 4;
  shape_7[2] = 8400;
  struct csinn_tensor *output_7 = csinn_alloc_tensor(sess);
  output_7->name = "output_7";
  output_7->dtype = CSINN_DTYPE_FLOAT16;
  output_7->layout = CSINN_LAYOUT_NCW;
  output_7->dim[0] = 1;
  output_7->dim[1] = 4;
  output_7->dim[2] = 8400;
  output_7->dim_count = 3;
  output_7->qinfo = (struct csinn_quant_info *)(params_base + 248);
  output_7->quant_channel = 1;
  struct csinn_reshape_params *params_7 = csinn_alloc_params(sizeof(struct csinn_reshape_params), sess);
  params_7->shape = shape_7;
  params_7->shape_num = 3;
  params_7->base.name = "reshape_/model.22/dfl/Reshape_1_6";
  params_7->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_reshape_init(output_6, output_7, params_7);
  int32_t *begin_8 = malloc(3 * 4);
  int32_t *end_8 = malloc(3 * 4);
  begin_8[0] = 0;
  begin_8[1] = 0;
  begin_8[2] = 0;
  end_8[0] = 1;
  end_8[1] = 2;
  end_8[2] = 8400;
  int32_t *strides_8 = malloc(3 * 4);
  strides_8[0] = 1;
  strides_8[1] = 1;
  strides_8[2] = 1;
  struct csinn_tensor *output_8 = csinn_alloc_tensor(sess);
  output_8->name = "output_8";
  output_8->dtype = CSINN_DTYPE_FLOAT16;
  output_8->layout = CSINN_LAYOUT_NCW;
  output_8->dim[0] = 1;
  output_8->dim[1] = 2;
  output_8->dim[2] = 8400;
  output_8->dim_count = 3;
  output_8->qinfo = (struct csinn_quant_info *)(params_base + 272);
  output_8->quant_channel = 1;
  struct csinn_strided_slice_params *params_8 = csinn_alloc_params(sizeof(struct csinn_strided_slice_params), sess);
  params_8->begin = begin_8;
  params_8->end = end_8;
  params_8->stride = strides_8;
  params_8->slice_count = 3;
  params_8->base.name = "strided_slice_/model.22/Slice_7";
  params_8->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_strided_slice_init(output_7, output_8, params_8);
  struct csinn_tensor *output_9 = csinn_alloc_tensor(sess);
  output_9->name = "output_9";
  output_9->dtype = CSINN_DTYPE_FLOAT16;
  output_9->layout = CSINN_LAYOUT_NCW;
  output_9->dim[0] = 1;
  output_9->dim[1] = 2;
  output_9->dim[2] = 8400;
  output_9->dim_count = 3;
  output_9->qinfo = (struct csinn_quant_info *)(params_base + 296);
  output_9->quant_channel = 1;
  struct csinn_tensor *lhs_0 = csinn_alloc_tensor(sess);
  lhs_0->name = "lhs_0";
  lhs_0->data = params_base + 344;
  lhs_0->is_const = 1;
  lhs_0->dtype = CSINN_DTYPE_FLOAT16;
  lhs_0->layout = CSINN_LAYOUT_OIW;
  lhs_0->dim[0] = 1;
  lhs_0->dim[1] = 2;
  lhs_0->dim[2] = 8400;
  lhs_0->dim_count = 3;
  lhs_0->qinfo = (struct csinn_quant_info *)(params_base + 320);
  lhs_0->quant_channel = 1;
  struct csinn_diso_params *params_9 = csinn_alloc_params(sizeof(struct csinn_diso_params), sess);
  params_9->base.name = "subtract_/model.22/Sub_8";
  params_9->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_sub_init(lhs_0, output_8, output_9, params_9);
  int32_t *begin_12 = malloc(3 * 4);
  int32_t *end_12 = malloc(3 * 4);
  begin_12[0] = 0;
  begin_12[1] = 2;
  begin_12[2] = 0;
  end_12[0] = 1;
  end_12[1] = 4;
  end_12[2] = 8400;
  int32_t *strides_12 = malloc(3 * 4);
  strides_12[0] = 1;
  strides_12[1] = 1;
  strides_12[2] = 1;
  struct csinn_tensor *output_12 = csinn_alloc_tensor(sess);
  output_12->name = "output_12";
  output_12->dtype = CSINN_DTYPE_FLOAT16;
  output_12->layout = CSINN_LAYOUT_NCW;
  output_12->dim[0] = 1;
  output_12->dim[1] = 2;
  output_12->dim[2] = 8400;
  output_12->dim_count = 3;
  output_12->qinfo = (struct csinn_quant_info *)(params_base + 33944);
  output_12->quant_channel = 1;
  struct csinn_strided_slice_params *params_12 = csinn_alloc_params(sizeof(struct csinn_strided_slice_params), sess);
  params_12->begin = begin_12;
  params_12->end = end_12;
  params_12->stride = strides_12;
  params_12->slice_count = 3;
  params_12->base.name = "strided_slice_/model.22/Slice_1_9";
  params_12->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_strided_slice_init(output_7, output_12, params_12);
  struct csinn_tensor *output_14 = csinn_alloc_tensor(sess);
  output_14->name = "output_14";
  output_14->dtype = CSINN_DTYPE_FLOAT16;
  output_14->layout = CSINN_LAYOUT_NCW;
  output_14->dim[0] = 1;
  output_14->dim[1] = 2;
  output_14->dim[2] = 8400;
  output_14->dim_count = 3;
  output_14->qinfo = (struct csinn_quant_info *)(params_base + 33968);
  output_14->quant_channel = 1;
  struct csinn_tensor *rhs_14 = csinn_alloc_tensor(sess);
  rhs_14->name = "rhs_14";
  rhs_14->data = params_base + 34016;
  rhs_14->is_const = 1;
  rhs_14->dtype = CSINN_DTYPE_FLOAT16;
  rhs_14->layout = CSINN_LAYOUT_OIW;
  rhs_14->dim[0] = 1;
  rhs_14->dim[1] = 2;
  rhs_14->dim[2] = 8400;
  rhs_14->dim_count = 3;
  rhs_14->qinfo = (struct csinn_quant_info *)(params_base + 33992);
  rhs_14->quant_channel = 1;
  struct csinn_diso_params *params_14 = csinn_alloc_params(sizeof(struct csinn_diso_params), sess);
  params_14->base.name = "add_/model.22/Add_1_10";
  params_14->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_add_init(output_12, rhs_14, output_14, params_14);
  struct csinn_tensor *output_16 = csinn_alloc_tensor(sess);
  output_16->name = "output_16";
  output_16->dtype = CSINN_DTYPE_FLOAT16;
  output_16->layout = CSINN_LAYOUT_NCW;
  output_16->dim[0] = 1;
  output_16->dim[1] = 2;
  output_16->dim[2] = 8400;
  output_16->dim_count = 3;
  output_16->qinfo = (struct csinn_quant_info *)(params_base + 67616);
  output_16->quant_channel = 1;
  struct csinn_diso_params *params_16 = csinn_alloc_params(sizeof(struct csinn_diso_params), sess);
  params_16->base.name = "add_/model.22/Add_2_11";
  params_16->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_add_init(output_9, output_14, output_16, params_16);
  struct csinn_tensor *output_19 = csinn_alloc_tensor(sess);
  output_19->name = "output_19";
  output_19->dtype = CSINN_DTYPE_FLOAT16;
  output_19->layout = CSINN_LAYOUT_NCW;
  output_19->dim[0] = 1;
  output_19->dim[1] = 2;
  output_19->dim[2] = 8400;
  output_19->dim_count = 3;
  output_19->qinfo = (struct csinn_quant_info *)(params_base + 67640);
  output_19->quant_channel = 1;
  struct csinn_tensor *rhs_19 = csinn_alloc_tensor(sess);
  rhs_19->name = "rhs_19";
  rhs_19->data = params_base + 67688;
  rhs_19->is_const = 1;
  rhs_19->dtype = CSINN_DTYPE_FLOAT16;
  rhs_19->layout = CSINN_LAYOUT_O;
  rhs_19->dim[0] = 1;
  rhs_19->dim_count = 1;
  rhs_19->qinfo = (struct csinn_quant_info *)(params_base + 67664);
  rhs_19->quant_channel = 1;
  struct csinn_diso_params *params_19 = csinn_alloc_params(sizeof(struct csinn_diso_params), sess);
  params_19->base.name = "divide_/model.22/Div_1_12";
  params_19->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_mul_init(output_16, rhs_19, output_19, params_19);
  struct csinn_tensor *output_22 = csinn_alloc_tensor(sess);
  output_22->name = "output_22";
  output_22->dtype = CSINN_DTYPE_FLOAT16;
  output_22->layout = CSINN_LAYOUT_NCW;
  output_22->dim[0] = 1;
  output_22->dim[1] = 2;
  output_22->dim[2] = 8400;
  output_22->dim_count = 3;
  output_22->qinfo = (struct csinn_quant_info *)(params_base + 67692);
  output_22->quant_channel = 1;
  struct csinn_diso_params *params_22 = csinn_alloc_params(sizeof(struct csinn_diso_params), sess);
  params_22->base.name = "subtract_/model.22/Sub_1_13";
  params_22->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_sub_init(output_14, output_9, output_22, params_22);
  struct csinn_tensor *input_24_concat[2];
  struct csinn_tensor *output_24 = csinn_alloc_tensor(sess);
  output_24->name = "output_24";
  output_24->dtype = CSINN_DTYPE_FLOAT16;
  output_24->layout = CSINN_LAYOUT_NCW;
  output_24->dim[0] = 1;
  output_24->dim[1] = 4;
  output_24->dim[2] = 8400;
  output_24->dim_count = 3;
  output_24->qinfo = (struct csinn_quant_info *)(params_base + 67716);
  output_24->quant_channel = 1;
  struct csinn_concat_params *params_24 = csinn_alloc_params(sizeof(struct csinn_concat_params), sess);
  params_24->inputs_count = 2;
  params_24->axis = 1;
  params_24->base.name = "concatenate_/model.22/Concat_4_14";
  params_24->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_concat_init(input_24_concat, output_24, params_24);
  struct csinn_tensor *output_26 = csinn_alloc_tensor(sess);
  output_26->name = "output_26";
  output_26->dtype = CSINN_DTYPE_FLOAT16;
  output_26->layout = CSINN_LAYOUT_NCW;
  output_26->dim[0] = 1;
  output_26->dim[1] = 4;
  output_26->dim[2] = 8400;
  output_26->dim_count = 3;
  output_26->qinfo = (struct csinn_quant_info *)(params_base + 67740);
  output_26->quant_channel = 1;
  struct csinn_tensor *rhs_26 = csinn_alloc_tensor(sess);
  rhs_26->name = "rhs_26";
  rhs_26->data = params_base + 67788;
  rhs_26->is_const = 1;
  rhs_26->dtype = CSINN_DTYPE_FLOAT16;
  rhs_26->layout = CSINN_LAYOUT_OIW;
  rhs_26->dim[0] = 1;
  rhs_26->dim[1] = 1;
  rhs_26->dim[2] = 8400;
  rhs_26->dim_count = 3;
  rhs_26->qinfo = (struct csinn_quant_info *)(params_base + 67764);
  rhs_26->quant_channel = 1;
  struct csinn_diso_params *params_26 = csinn_alloc_params(sizeof(struct csinn_diso_params), sess);
  params_26->base.name = "multiply_/model.22/Mul_2_15";
  params_26->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_mul_init(output_24, rhs_26, output_26, params_26);
  struct csinn_tensor *output_28 = csinn_alloc_tensor(sess);
  output_28->name = "output_28";
  output_28->dtype = CSINN_DTYPE_FLOAT16;
  output_28->layout = CSINN_LAYOUT_NCW;
  output_28->dim[0] = 1;
  output_28->dim[1] = 2;
  output_28->dim[2] = 8400;
  output_28->dim_count = 3;
  output_28->qinfo = (struct csinn_quant_info *)(params_base + 84588);
  output_28->quant_channel = 1;
  struct csinn_sigmoid_params *params_28 = csinn_alloc_params(sizeof(struct csinn_sigmoid_params), sess);
  params_28->base.name = "sigmoid_/model.22/Sigmoid_16";
  params_28->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_sigmoid_init(output_1_1, output_28, params_28);
  struct csinn_tensor *input_29_concat[2];
  struct csinn_tensor *output_29 = csinn_alloc_tensor(sess);
  output_29->name = "output_29";
  output_29->dtype = CSINN_DTYPE_FLOAT16;
  output_29->layout = CSINN_LAYOUT_NCW;
  output_29->dim[0] = 1;
  output_29->dim[1] = 6;
  output_29->dim[2] = 8400;
  output_29->dim_count = 3;
  output_29->qinfo = (struct csinn_quant_info *)(params_base + 84612);
  output_29->quant_channel = 1;
  struct csinn_concat_params *params_29 = csinn_alloc_params(sizeof(struct csinn_concat_params), sess);
  params_29->inputs_count = 2;
  params_29->axis = 1;
  params_29->base.name = "concatenate_/model.22/Concat_5_17";
  params_29->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_concat_init(input_29_concat, output_29, params_29);
  int32_t *permute_30 = malloc(3 * 4);
  permute_30[0] = 0;
  permute_30[1] = 2;
  permute_30[2] = 1;
  struct csinn_tensor *output_30 = csinn_alloc_tensor(sess);
  output_30->name = "transpose_output0@@/model.22/Transpose_18_30";
  output_30->dtype = CSINN_DTYPE_FLOAT16;
  output_30->layout = CSINN_LAYOUT_NCW;
  output_30->dim[0] = 1;
  output_30->dim[1] = 8400;
  output_30->dim[2] = 6;
  output_30->dim_count = 3;
  output_30->qinfo = (struct csinn_quant_info *)(params_base + 84636);
  output_30->quant_channel = 1;
  struct csinn_transpose_params *params_30 = csinn_alloc_params(sizeof(struct csinn_transpose_params), sess);
  params_30->permute = permute_30;
  params_30->permute_num = 3;
  params_30->base.name = "transpose_output0@@/model.22/Transpose_18";
  params_30->base.quant_type = CSINN_QUANT_FLOAT16;
  csinn_transpose_init(output_29, output_30, params_30);
  csinn_set_tensor_entry(_model_22_Concat_3_output_0, sess);
  csinn_set_input(0, _model_22_Concat_3_output_0, sess);

  csinn_split(_model_22_Concat_3_output_0, output_1, params_1);
  csinn_reshape(output_1_0, output_2, params_2);
  csinn_transpose(output_2, output_3, params_3);
  csinn_softmax(output_3, output_4, params_4);
  csinn_transpose(output_4, output_5, params_5);
  csinn_conv2d(output_5, output_6, kernel_6, bias_6, params_6);
  csinn_reshape(output_6, output_7, params_7);
  csinn_strided_slice(output_7, output_8, params_8);
  csinn_sub(lhs_0, output_8, output_9, params_9);
  csinn_strided_slice(output_7, output_12, params_12);
  csinn_add(output_12, rhs_14, output_14, params_14);
  csinn_add(output_9, output_14, output_16, params_16);
  csinn_mul(output_16, rhs_19, output_19, params_19);
  csinn_sub(output_14, output_9, output_22, params_22);
  input_24_concat[0] = output_19;
  input_24_concat[1] = output_22;
  csinn_concat(input_24_concat, output_24, params_24);
  csinn_mul(output_24, rhs_26, output_26, params_26);
  csinn_sigmoid(output_1_1, output_28, params_28);
  input_29_concat[0] = output_26;
  input_29_concat[1] = output_28;
  csinn_concat(input_29_concat, output_29, params_29);
  csinn_transpose(output_29, output_30, params_30);
  csinn_set_output(0, output_30, sess);

  csinn_session_setup(sess);
  return sess;
}
void csinn_update_input_and_run(struct csinn_tensor **input_tensors , void *sess) {
  csinn_update_input(0, input_tensors[0], sess);
  csinn_session_run(sess);
}
